import express from 'express';
import { db } from '../firebase.js';

const router = express.Router();

router.post('/submit-loan', async (req, res) => {
  try {
    const {
      userId,
      ocrText,
      insurance,
      insuranceValid,
      estimatedOutOfPocket,
      status,
      timestamp,
      xrplTxHash,
      repayment
    } = req.body;

    // Create document in `loans` collection with autogenerated ID
    const docRef = await db.collection('loans').add({
      userId,
      ocrText,
      insurance,
      insuranceValid,
      estimatedOutOfPocket,
      status,
      timestamp: new Date(timestamp),
      xrplTxHash,
      repayment: {
        totalPaid: repayment.totalPaid,
        remaining: repayment.remaining,
        lastPaymentDate: new Date(repayment.lastPaymentDate),
      },
    });

    res.json({ message: 'Loan record created!', docId: docRef.id });
  } catch (err) {
    console.error('Firestore Write Error:', err);
    res.status(500).json({ error: 'Failed to write loan record' });
  }
});

export default router;
